openapi: 3.0.3
info:
  title: API de Câmbio de Moedas Fantásticas
  version: 1.0.0
  description: >
    API para consultar taxas de câmbio e realizar conversões de moeda com base em produtos negociáveis
    entre moedas do mundo fantástico, como Ouro Real e Tibar. A taxa pode variar de acordo com o tipo de produto.

tags:
  - name: Cambio
    description: Operações relacionadas à consulta e conversão de taxas de câmbio entre moedas.
  - name: Produtos
    description: Operações para listar, criar e consultar produtos negociáveis.
  - name: Reinos
    description: Gerenciamento dos reinos e suas respectivas moedas.
  - name: Moedas
    description: Gerenciamento das moedas utilizadas nos reinos e conversões.

paths:
  /cambio:
    get:
      tags:
        - Cambio
      summary: Consulta taxa de câmbio entre duas moedas para um produto
      description: >
        Retorna a taxa de câmbio entre duas moedas específicas (como OURO_REAL e TIBAR), levando em conta
        o produto negociado. Se nenhum produto for informado, será utilizada a taxa padrão entre as moedas.
      parameters:
        - in: query
          name: moedaOrigem
          required: true
          schema:
            type: string
          description: Código da moeda de origem (ex OURO_REAL).
        - in: query
          name: moedaDestino
          required: true
          schema:
            type: string
          description: Código da moeda de destino (ex TIBAR).
        - in: query
          name: produto
          required: false
          schema:
            type: string
          description: Nome do produto a ser negociado (ex PELES). Se omitido, será usada a taxa padrão.
      responses:
        '200':
          description: Taxa de câmbio encontrada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxaCambioResponse'
        '404':
          description: Taxa de câmbio não encontrada para os parâmetros informados.

  /cambio/conversao:
    post:
      tags:
        - Cambio
      summary: Converte valor entre moedas com base em um produto
      description: >
        Realiza a conversão de um valor entre moedas do mundo fantástico, considerando a taxa de câmbio
        para o produto especificado. As taxas variam conforme o produto negociado.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversaoRequest'
      responses:
        '200':
          description: Conversão realizada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversaoResponse'
        '400':
          description: Requisição inválida. Verifique os dados enviados.

  /produtos:
    get:
      tags:
        - Produtos
      summary: Lista todos os produtos disponíveis para negociação
      description: Retorna todos os produtos registrados no sistema que podem influenciar nas taxas de câmbio.
      responses:
        '200':
          description: Lista de produtos retornada com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'
    post:
      tags:
        - Produtos
      summary: Cadastra um novo produto negociável
      description: Adiciona um novo produto ao sistema. Produtos podem alterar as taxas de câmbio entre moedas.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        '201':
          description: Produto criado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        '409':
          description: Já existe um produto com o mesmo nome.

  /produtos/{id}:
    get:
      tags:
        - Produtos
      summary: Busca detalhes de um produto pelo ID
      description: Retorna as informações de um produto específico através de seu identificador único.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Produto encontrado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        '404':
          description: Produto não encontrado.

  /reinos:
    get:
      tags:
        - Reinos
      summary: Lista todos os reinos registrados
      description: Retorna todos os reinos fantásticos cadastrados, com seus respectivos nomes e moedas.
      responses:
        '200':
          description: Lista de reinos retornada com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reino'
    post:
      tags:
        - Reinos
      summary: Cria um novo reino
      description: Adiciona um novo reino ao mundo fantástico e associa uma moeda à ele.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reino'
      responses:
        '201':
          description: Reino criado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reino'
        '409':
          description: Já existe um reino com esse nome.

  /reinos/{id}:
    get:
      tags:
        - Reinos
      summary: Consulta um reino pelo ID
      description: Retorna as informações detalhadas de um reino através de seu identificador.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Reino encontrado com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reino'
        '404':
          description: Reino não encontrado.

  /moedas:
    get:
      tags:
        - Moedas
      summary: Lista todas as moedas do sistema
      description: Retorna as moedas cadastradas no mundo fantástico, como OURO_REAL e TIBAR.
      responses:
        '200':
          description: Lista de moedas retornada com sucesso.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Moeda'
    post:
      tags:
        - Moedas
      summary: Cria uma nova moeda
      description: Adiciona uma nova moeda ao sistema para ser utilizada em transações e conversões.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Moeda'
      responses:
        '201':
          description: Moeda criada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Moeda'
        '409':
          description: Já existe uma moeda com esse nome.

  /moedas/{id}:
    get:
      tags:
        - Moedas
      summary: Busca detalhes de uma moeda pelo ID
      description: Retorna os dados de uma moeda específica através de seu identificador único.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Moeda encontrada com sucesso.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Moeda'
        '404':
          description: Moeda não encontrada.

components:
  schemas:
    Moeda:
      type: object
      description: Moeda utilizada nas conversões.
      properties:
        id:
          type: integer
          format: int64
          description: Identificador único da moeda.
          example: 1
        nome:
          type: string
          description: Nome da moeda.
          example: OURO_REAL
      required:
        - id
        - nome

    Produto:
      type: object
      description: Produto negociável.
      properties:
        id:
          type: integer
          format: int64
          description: Identificador único do produto.
          example: 1
        nome:
          type: string
          description: Nome do produto.
          example: PELES
      required:
        - id
        - nome

    Reino:
      type: object
      description: Reino fantástico.
      properties:
        id:
          type: integer
          format: int64
          description: Identificador único do reino.
          example: 1
        nome:
          type: string
          description: Nome do reino.
          example: SRM
        moedaId:
          type: integer
          example: 2
      required:
        - nome
        - moedaId

    TaxaCambioResponse:
      type: object
      properties:
        moedaOrigem:
          type: string
          description: Nome da moeda de origem.
          example: "OURO_REAL"
        moedaDestino:
          type: string
          description: Nome da moeda de destino.
          example: "TIBAR"
        produto:
          type: string
          description: Nome do produto utilizado para influenciar a taxa.
          example: "PELES"
        taxa:
          type: number
          format: double
          description: Valor da taxa de conversão entre as moedas.
          example: 1.5
        dataAtualizacao:
          type: string
          format: date-time
          description: Data e hora em que a taxa foi atualizada.
          example: "2025-05-14T13:45:00Z"

    ConversaoRequest:
      type: object
      required:
        - moedaOrigem
        - moedaDestino
        - produto
        - valor
      properties:
        moedaOrigem:
          type: string
          description: Nome da moeda de origem.
          example: "OURO_REAL"
        moedaDestino:
          type: string
          description: Nome da moeda de destino.
          example: "TIBAR"
        produto:
          type: string
          description: Nome do produto associado à conversão.
          example: "MADEIRA"
        valor:
          type: number
          format: double
          description: Valor a ser convertido.
          example: 100.0

    ConversaoResponse:
      type: object
      required:
        - moedaOrigem
        - moedaDestino
        - produto
        - valorConvertido
        - taxaAplicada
        - dataHora
      properties:
        moedaOrigem:
          type: string
        moedaDestino:
          type: string
        produto:
          type: string
        valorConvertido:
          type: number
          format: double
        taxaAplicada:
          type: number
          format: double
        dataHora:
          type: string
          format: date-time

