openapi: 3.0.3
info:
  title: API de Câmbio de Moedas Fantásticas
  version: 1.0.0
  description: >
    API para consultar taxas de câmbio e realizar trocas de moeda por produto
    entre moedas do mundo fantástico: Ouro Real e Tibar.

paths:
  /cambio:
    get:
      summary: Consulta a taxa de câmbio atual entre moedas
      description: Retorna a taxa de conversão entre duas moedas específicas, considerando um produto negociado.
      parameters:
        - in: query
          name: moedaOrigem
          required: true
          schema:
            type: string
          description: Nome da moeda que será convertida (ex OURO_REAL).
        - in: query
          name: moedaDestino
          required: true
          schema:
            type: string
          description: Nome da moeda de destino da conversão (ex TIBAR).
        - in: query
          name: produto
          required: false
          schema:
            type: string
          description: Nome do produto negociado que influencia a taxa de conversão (ex PELES). Se não informado, será usada a taxa padrão (quando aplicável).
      responses:
        '200':
          description: Taxa de câmbio entre moedas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxaCambioResponse'
        '404':
          description: Taxa de câmbio não encontrada para os parâmetros fornecidos.

  /cambio/conversao:
    post:
      summary: Realiza a conversão de moeda para um produto
      description: Converte um valor de uma moeda para outra com base em um produto negociado,
        considerando regras específicas de conversão para cada tipo de produto.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConversaoRequest'
      responses:
        '200':
          description: Conversão realizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversaoResponse'
        '400':
          description: Requisição inválida. Verifique os dados enviados.

  /produtos:
    get:
      summary: Lista todos os produtos disponíveis
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'
    post:
      summary: Cria um novo produto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        '201':
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        '409':
          description: Produto já existe

  /produtos/{id}:
    get:
      summary: Busca um produto pelo ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Produto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produto'
        '404':
          description: Produto não encontrado

  /reinos:
    get:
      summary: Lista todos os reinos disponíveis
      responses:
        '200':
          description: Lista de reinos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reino'
    post:
      summary: Cria um novo reino
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reino'
      responses:
        '201':
          description: Reino criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reino'
        '409':
          description: Reino já existe

  /reinos/{id}:
    get:
      summary: Busca um reino pelo ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Reino encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reino'
        '404':
          description: Reino não encontrado

  /moedas:
    get:
      summary: Lista todas as moedas disponíveis
      responses:
        '200':
          description: Lista de moedas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Moeda'
    post:
      summary: Cria uma nova moeda
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Moeda'
      responses:
        '201':
          description: Moeda criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Moeda'
        '409':
          description: Moeda já existe

  /moedas/{id}:
    get:
      summary: Busca uma moeda pelo ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Moeda encontrada
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Moeda'
        '404':
          description: Moeda não encontrada


components:
  schemas:
    Moeda:
      type: object
      description: Moeda utilizada nas conversões.
      properties:
        id:
          type: integer
          format: int64
          description: Identificador único da moeda.
          example: 1
        nome:
          type: string
          description: Nome da moeda.
          example: OURO_REAL
      required:
        - id
        - nome

    Produto:
      type: object
      description: Produto negociável.
      properties:
        id:
          type: integer
          format: int64
          description: Identificador único do produto.
          example: 1
        nome:
          type: string
          description: Nome do produto.
          example: PELES
      required:
        - id
        - nome

    Reino:
      type: object
      description: Reino fantástico.
      properties:
        id:
          type: integer
          format: int64
          description: Identificador único do reino.
          example: 1
        nome:
          type: string
          description: Nome do reino.
          example: SRM
        moedaId:
          type: integer
          example: 2
      required:
        - nome
        - moedaId

    TaxaCambioResponse:
      type: object
      properties:
        moedaOrigem:
          type: string
          description: Nome da moeda de origem.
          example: "OURO_REAL"
        moedaDestino:
          type: string
          description: Nome da moeda de destino.
          example: "TIBAR"
        produto:
          type: string
          description: Nome do produto utilizado para influenciar a taxa.
          example: "PELES"
        taxa:
          type: number
          format: double
          description: Valor da taxa de conversão entre as moedas.
          example: 1.5
        dataAtualizacao:
          type: string
          format: date-time
          description: Data e hora em que a taxa foi atualizada.
          example: "2025-05-14T13:45:00Z"

    ConversaoRequest:
      type: object
      required:
        - moedaOrigem
        - moedaDestino
        - produto
        - valor
      properties:
        moedaOrigem:
          type: string
          description: Nome da moeda de origem.
          example: "OURO_REAL"
        moedaDestino:
          type: string
          description: Nome da moeda de destino.
          example: "TIBAR"
        produto:
          type: string
          description: Nome do produto associado à conversão.
          example: "MADEIRA"
        valor:
          type: number
          format: double
          description: Valor a ser convertido.
          example: 100.0

    ConversaoResponse:
      type: object
      required:
        - moedaOrigem
        - moedaDestino
        - produto
        - valorConvertido
        - taxaAplicada
        - dataHora
      properties:
        moedaOrigem:
          type: string
        moedaDestino:
          type: string
        produto:
          type: string
        valorConvertido:
          type: number
          format: double
        taxaAplicada:
          type: number
          format: double
        dataHora:
          type: string
          format: date-time
